apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app
  labels:
    app: my-go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-go-app
  template:
    metadata:
      labels:
        app: my-go-app
    spec:
      containers:
      - name: my-go-app
        image: aswini282/mygo:latest
      imagePullSecrets:
      - name: myregistrykey
